name: webcam
version: ${version}
main: ru.dimaskama.webcam.spigot.WebcamSpigot
api-version: 1.21
description: Webcams in Minecraft
author: DimasKama
commands:
  webcamconfig:
    description: "Command for modifying Webcam server config"
    permission: webcam.command.config
    permission-message: "You do not have permission to modify Webcam server config"
    usage: "/webcamconfig <field> [new_value]"
permissions:
  webcam.command.config:
    default: op
    description: "Allows to modify Webcam server config"
  webcam.broadcast:
    default: true
    description: "Allows to broadcast webcam"
  webcam.view:
    default: true
    description: "Allows to view players' webcams"