mod_loader=fabric

included_projects=:common, :common-mod

# Fabric API
import_fabric_api=true
fabric_loader_version=0.19.3
fabric_api_version=0.152.1+26.2

fabric_permissions_api_version=0.7.0
modmenu_version=20.0.0-beta.2
flashback_version=0.39.3-fabric,26.1
replaymod_version=1.21.7-2.6.23

modrinth_upload_required_dependencies=fabric-api
modrinth_upload_optional_dependencies=modmenu,cloth-config
