# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

mod_version=4.4.1-26.2
maven_group=net.dimaskama
mod_id=webcam
mod_display_name=Webcam
mod_authors=DimasKama
minecraft_user_name_prefix=DimasKama
random_minecraft_user_name=false

java_version=25
java_toolchain_version=25

minecraft_version=26.2

min_minecraft_version=26.2

netty_version=4.2.15.Final
datafixerupper_version=10.0.21
joml_version=1.10.8

opencv_version=4.9.0-0
javah264_version=0.0.2
iris_version=1.11.1+26.2
cloth_config_version=26.2.155

mod_gradle_script_version=1.0.61

shadow_version=9.3.2
minotaur_version=2.+
fabric_loom_version=1.17-SNAPSHOT
paperweight_version=2.0.0-beta.21
run_task_version=3.0.0
moddevgradle_version=2.0.+

enable_curseforge_upload=false
enable_mod_update=false

upload_release_type=release

modrinth_upload_id=KLTWlg59
modrinth_upload_include_prefix=false
modrinth_upload_supported_game_versions=26.2
